---
jenkins:
  systemMessage: "Jenkins As Code Concept."
  views:
    - myView:
        name: "Jobs Config as Code"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
tool:
  git:
    installations:
      - name: Default
        home: "git"
jobs:
  - script: >
      pipelineJob('Jobs Generator') {
          definition {
              triggers {
                  cron('H/5 * * * *')
              }
              cpsScm {
                  scm {
                    git {
                        remote { url 'https://github.com/Kostua/jenkins_as_code_jobs.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
                  scriptPath '*.groovy'
              }
          }
      }