---
jenkins:
  systemMessage: "Jenkins As Code Concept."
  views:
    - myView:
        name: "Jobs Config as Code"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
tool:
  nodejs:
    installations:
    - name: "NodeJS Latest"
      home: "" #required until nodejs-1.3.4 release (JENKINS-57508)
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "12.11.1"
              npmPackagesRefreshHours: 48 #default is 72
  maven:
    installations:
    - name: "M3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.6.3"
jobs:
  - script: >
      freeStyleJob('JobsGenerator') {
        triggers {
                    hudsonStartupTrigger {
                      quietPeriod("60")
                      runOnChoice("ON_CONNECT")
                      label("")
                      nodeParameterName("")
                }
          }
        scm {
            github('Kostua/jenkins_as_code_jobs', 'master')
        }
        steps {
            dsl {
              external('*.groovy')
            }
        }
      }
  - script: >
      queue('JobsGenerator')